# These are supported funding model platforms

github: [tpfkalrrltk, Jelo777, seungseok2, user7198548, yejishin95]
patreon: tpfkalrrltk
tidelift: npm/octo-package
custom: ["https://www.paypal.me/octocat", octocat.com]
